=== hispin/dhis-core-trunk/dhis-live/src/main/resources/Config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.dhis.org/schema/config"
    targetNamespace="http://www.dhis.org/schema/config" elementFormDefault="qualified">

    <xs:complexType name="ConfigType">
        <xs:sequence>
            <xs:element name="AppConfiguration">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="LocaleLanguage" type="xs:string" default="en"/>
                        <xs:element name="LocaleCountry" type="xs:string" default=""/>
                        <xs:element name="Port" type="xs:int" default="8080"/>
                        <xs:element name="Host" type="xs:string" default="localhost"/>
                        <xs:element name="PreferredBrowser" type="xs:string" default=""/>
                        <xs:element name="MaxFormContentSize" type="xs:int" default="400000"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="DatabaseConfiguration">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="ConnectionTypes">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="ConnectionType" maxOccurs="unbounded">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="Dialect" type="xs:string"/>
                                                <xs:element name="DriverClass" type="xs:string"/>
                                            </xs:sequence>
                                            <xs:attribute name="id" type="xs:ID" use="required"/>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="DatabaseConnections">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="Connection" maxOccurs="unbounded">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="Name" type="xs:string"/>
                                                <xs:element name="URL" type="xs:string"/>
                                                <xs:element name="UserName" type="xs:string"/>
                                                <xs:element name="Password" type="xs:string"
                                                  default="" minOccurs="0"/>
                                            </xs:sequence>
                                            <xs:attribute name="type" type="xs:IDREF" use="required"/>
                                            <xs:attribute name="id" type="xs:ID" use="required"/>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                                <xs:attribute name="selected" type="xs:IDREF" use="required"/>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="Config" type="ConfigType"> </xs:element>

</xs:schema>

=== hispin/dhis-core-trunk/dhis-live/src/main/resources/defaultConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Default configuration for dhis2-live -->
<!-- Bob Jolliffe 07/09/2010 -->

<Config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.dhis.org/schema/config Config.xsd"
 xmlns="http://www.dhis.org/schema/config">
    <AppConfiguration>
        <LocaleLanguage>en</LocaleLanguage>
        <LocaleCountry>GB</LocaleCountry>
        <Port>8080</Port>
        <Host>localhost</Host>
        <PreferredBrowser/>
        <MaxFormContentSize>200000</MaxFormContentSize>
    </AppConfiguration>
    <DatabaseConfiguration>
        <ConnectionTypes>
            <ConnectionType id="h2">
                <Dialect>org.hisp.dhis.dialect.H2Dialect</Dialect>
                <DriverClass>org.h2.Driver</DriverClass>
            </ConnectionType>
            <ConnectionType id="mysql">
                <Dialect>org.hibernate.dialect.MySQLDialect</Dialect>
                <DriverClass>com.mysql.jdbc.Driver</DriverClass>
            </ConnectionType>
            <ConnectionType id="postgres">
                <Dialect>org.hibernate.dialect.PostgreSQLDialect</Dialect>
                <DriverClass>org.postgresql.Driver</DriverClass>
            </ConnectionType>
        </ConnectionTypes>
        <DatabaseConnections selected="conn1">
            <Connection id="conn1" type="h2">
                <Name>DHIS2 Demo</Name>
                <URL>jdbc:h2:./database/demo;AUTO_SERVER=TRUE</URL>
                <UserName>sa</UserName>
            </Connection>
        </DatabaseConnections>
    </DatabaseConfiguration>
</Config>
